on: push
name: Clippy check
jobs:
  clippy_check:
    runs-on: ubuntu-24.04
    steps:
      - uses: actions/checkout@v1
      - name: install dependencies (ubuntu only)
        run: |
          sudo apt-get update
          sudo apt-get install -y libglib2.0-dev libgtk-3-dev

      - uses: actions-rs/toolchain@v1
        with:
            toolchain: nightly
            components: clippy
            override: true
      - uses: actions-rs/clippy-check@v1
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          args: --all --manifest-path ./src-tauri/Cargo.toml -- -D warnings